apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysmon
  labels:
    app: sysmon-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sysmon-webapp
  template:
    metadata:
      labels:
        app: sysmon-webapp
    spec:
      containers:
        - name: sysmon-webapp
          image: basebandit.jfrog.io/docker/sysmon:1.0.1
          ports:
            - containerPort: 5000
