#!/usr/bin/env groovy
pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = 'us-east-1'
    }
    stages {
        stage('Create an EKS cluster') {
      steps {
        script {
          def workingDir = "${workspace}/eks-deploy"
          dir(workingDir) {
            sh 'terraform init'
            sh 'terraform state rm "aws_s3_bucket.sysmon_tfstate_bucket"'
            sh 'terraform import "aws_s3_bucket.sysmon_tfstate_bucket" "sysmon-app-bucket"'
            sh 'terraform apply -auto-approve'
          }
        }
      }
        }
        stage('Deploy to EKS') {
      steps {
        script {
          def kubernetesDir = "${workspace}/kubernetes"
          dir(kubernetesDir) {
            sh 'aws eks update-kubeconfig --name sysmon-eks-cluster'
            sh 'kubectl apply -f deployment.yaml'
            sh 'kubectl apply -f service.yaml'
          }
        }
      }
        }
    }
}
